Feature/scan file
PopcodeMobile/barcode-finder pull request #4
Opened 2020-12-22 12:23 UTC by aquilarafa

2021-01-05 14:03 UTC, isthaynny commented
Teste com um boleto da Nubank no android, mas o código de barra lido é diferente ao do boleto.

https://user-images.githubusercontent.com/66264766/103654696-f9aa7380-4f44-11eb-81a9-8c753b65db6e.png
https://user-images.githubusercontent.com/66264766/103654839-2bbbd580-4f45-11eb-92e3-051cad90d691.jpeg

2021-01-05 14:16 UTC, muriloformiga commented
> Teste com um boleto da Nubank no android, mas o código de barra lido é diferente ao do boleto.
> 
> https://user-images.githubusercontent.com/66264766/103654696-f9aa7380-4f44-11eb-81a9-8c753b65db6e.png
> https://user-images.githubusercontent.com/66264766/103654839-2bbbd580-4f45-11eb-92e3-051cad90d691.jpeg

@isthaynny isso acontece porque o Brasil usa um padrão diferenciado para numerar os boletos. O código que podemos observar acima das barras é chamado _linha digitável_, que de fato não é equivalente àquele extraído pelos leitores de imagem  através do padrão das barras.

Você pode usar o site https://online-barcode-reader.inliteresearch.com/ para constatar que a leitura do barcode_finder está correta.

O que nós possívelmente faremos é mandar os dados lidos para o backend converter em linha digitável (padrão Brasil).

2021-01-05 14:32 UTC, ThiagoFontes commented on README.md
> +Make sure you have to pass a valid and permissioned path to `BarcodeFinder.scanFile`, in exemple above File Picker do it for us.
Acho que ficaria melhor assim:
Make sure you are passing a valid and permissioned path...
...in the provided example above, the package FilePicker provides it for us

2021-01-05 14:35 UTC, ThiagoFontes commented on README.md
> +  barcode_finder: last version
Acho que seria melhor usar latest no lugar de last aqui

2021-01-05 14:36 UTC, ThiagoFontes commented on android/build.gradle
> +    //implementation 'androidx.appcompat:appcompat:1.0.2'
Lembrar de remover os comentários de código antigo

2021-01-05 14:59 UTC, ThiagoFontes commented
Tem um gif de 10.2 MB no código de exemplo, este arquivo não irá junto com a biblioteca? Talvez seja melhor remover para reduzir o tamanho do package.

2021-01-05 16:39 UTC, muriloformiga commented
> Tem um gif de 10.2 MB no código de exemplo, este arquivo não irá junto com a biblioteca? Talvez seja melhor remover para reduzir o tamanho do package.

Pelo que observei olhando o código de um projeto que usa o File Picker, que também tem um GIF no README, ele vai junto com a instalação do plugin no projeto. Provavelmente não é considerado na build da aplicação, mas pode ser um inconveniente para usuários do plugin baixar arquivos grandes desnecessários.

Qual a melhor solução para nosso caso? remover o gif, procurar uma forma de diminuir expressivamente seu tamanho ou hospedá-lo em um outro serviço, fazendo apenas referência ao link?

2021-01-06 19:46 UTC, ThiagoFontes commented
> > Tem um gif de 10.2 MB no código de exemplo, este arquivo não irá junto com a biblioteca? Talvez seja melhor remover para reduzir o tamanho do package.
> 
> Pelo que observei olhando o código de um projeto que usa o File Picker, que também tem um GIF no README, ele vai junto com a instalação do plugin no projeto. Provavelmente não é considerado na build da aplicação, mas pode ser um inconveniente para usuários do plugin baixar arquivos grandes desnecessários.
> 
> Qual a melhor solução para nosso caso? remover o gif, procurar uma forma de diminuir expressivamente seu tamanho ou hospedá-lo em um outro serviço, fazendo apenas referência ao link?

Acredito que o próprio GitHub poderia hospedar o gif do readme sem problemas.

2021-01-06 19:48 UTC, ThiagoFontes commented on android/src/main/kotlin/br/com/popcode/barcode_finder/BarcodeFinderPlugin.kt
> +  }
Essa função para obter a versão do Android é utilizada em algum lugar?

2021-01-07 11:35 UTC, ThiagoFontes requested changes

2021-01-07 11:35 UTC, ThiagoFontes commented on example/test/widget_test.dart
> +  });
Teste que não condiz com o exemplo do plugin, remover ou substituir por outro.

2021-01-07 11:40 UTC, ThiagoFontes commented on test/barcode_finder_test.dart
> +  });
Acredito que este também seja o teste de exemplo do Flutter, mesma condição do comentado anteriormente.

2021-03-15 12:30 UTC, isadoraLima21 commented on ios/Classes/GetBarcodeFromImage.swift
> +            print("ZXing: barcode found - \(barcode)")
Remover prints :)

2021-03-15 12:34 UTC, ThiagoFontes approved these changes

2021-03-15 12:55 UTC, isadoraLima21 approved these changes

2021-03-15 13:57 UTC, isthaynny approved these changes

2021-08-16 19:32 UTC, merged